"""Add enabled_modules_list to Organization

Revision ID: 24647a567f92
Revises: e3b1c4d5f6a7
Create Date: 2026-04-29 23:21:19.681133

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '24647a567f92'
down_revision = 'e3b1c4d5f6a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_org_active_search_text'))
        batch_op.drop_index(batch_op.f('ix_documents_org_ai_analysis_at'))
        batch_op.drop_index(batch_op.f('ix_documents_search_text_tsv'), postgresql_using='gin')

    with op.batch_alter_table('organization_memberships', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_org_memberships_role_id'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'rbac_roles', ['role_id'], ['id'])

    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enabled_modules_list', sa.Text(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_organizations_billing_status'))
        batch_op.drop_index(batch_op.f('ix_organizations_stripe_customer_id'))

    with op.batch_alter_table('rbac_roles', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('rbac_roles_organization_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'organizations', ['organization_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rbac_roles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('rbac_roles_organization_id_fkey'), 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)

    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizations_stripe_customer_id'), ['stripe_customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_organizations_billing_status'), ['billing_status'], unique=False)
        batch_op.drop_column('enabled_modules_list')

    with op.batch_alter_table('organization_memberships', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_org_memberships_role_id'), 'rbac_roles', ['role_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_search_text_tsv'), [sa.literal_column("to_tsvector('simple'::regconfig, COALESCE(search_text, ''::text))")], unique=False, postgresql_using='gin')
        batch_op.create_index(batch_op.f('ix_documents_org_ai_analysis_at'), ['organization_id', 'ai_analysis_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_org_active_search_text'), ['organization_id', 'is_active'], unique=False)

    # ### end Alembic commands ###
