"""walkthroughs_enabled

Revision ID: 9aefa99727b2
Revises: a779433ee474
Create Date: 2026-05-15 13:22:38.529689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9aefa99727b2'
down_revision = 'a779433ee474'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization_ai_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('walkthroughs_enabled', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization_ai_settings', schema=None) as batch_op:
        batch_op.drop_column('walkthroughs_enabled')

    # ### end Alembic commands ###
