"""extend_ai_usage_event_with_feedback_columns

Revision ID: a3951fc69dc1
Revises: 9aefa99727b2
Create Date: 2026-05-17 15:34:26.080839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3951fc69dc1'
down_revision = '9aefa99727b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_usage_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('document_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('feedback_status', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('feedback_confidence', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('feedback_reason', sa.Text(), nullable=True))
        batch_op.create_foreign_key(None, 'documents', ['document_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_usage_events', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('feedback_reason')
        batch_op.drop_column('feedback_confidence')
        batch_op.drop_column('feedback_status')
        batch_op.drop_column('document_id')

    # ### end Alembic commands ###
